# Generated by Django 2.2.5 on 2020-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_auto_20200516_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtousefood',
            name='how_to_store',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='howtousefood',
            name='how_to_trim',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
